services:
  - type: web
    name: hush-server
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
