services:
  - type: web
    name: websocket-server
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "npm run start"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
