services:
  - type: web
    name: hush-server
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
